version: "3"
services: 
  jenkins:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
        - "8080:8080"
    volumes: 
      - ~/mnt/jenkins:/var/jenkins_home
